### ISSUE TITLE
Can't run example after installation

### ISSUE THREAD

**Issue by Kaligule** [lantunes/netomaton#2]
Hi, thanks for this very interessting project.

I am running `Python 3.7.6`, installed `netomaton` (0.2.0) (note that I did not pull the repository, only install it via pip) and copied the `requirements` file to install that, too. Then I tried to run example from the readme.

```
Traceback (most recent call last):
  File "example_from_readme.py", line 1, in <module>
    import netomaton as ntm
  File "/Users/username/test_network_automata/venv/lib/python3.7/site-packages/netomaton/__init__.py", line 3, in <module>
    from .asynchronous_rule import *
  File "/Users/username/test_network_automata/venv/lib/python3.7/site-packages/netomaton/asynchronous_rule.py", line 2, in <module>
    from .rules import *
ModuleNotFoundError: No module named 'netomaton.rules'
```

I am not sure what happens here.

**Comment by Kaligule** [comment]
Looking over it again, I think it had to do with my python setup. Sorry for the inconvenience.

**Comment by lantunes** [comment]
Hi, thanks for reporting this! Another user just reported the same problem, and it was because of a problem with the `setup.py` file. I have fixed the problem and created a new release, version `0.2.1`.
