### ISSUE TITLE
subpackage not found

### ISSUE THREAD

**Issue by kzuberi** [lantunes/netomaton#3]
Interesting looking package! Not sure if I'm doing something wrong, but installing version 0.2.0 with pip gives:

```python
Python 3.7.5 (default, Oct 25 2019, 15:51:11) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import netomaton
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kz/miniconda2/envs/py3misc/lib/python3.7/site-packages/netomaton/__init__.py", line 3, in <module>
    from .asynchronous_rule import *
  File "/home/kz/miniconda2/envs/py3misc/lib/python3.7/site-packages/netomaton/asynchronous_rule.py", line 2, in <module>
    from .rules import *
ModuleNotFoundError: No module named 'netomaton.rules'
```

Works fine when checked out from git locally though. Maybe a packaging issue?

**Comment by lantunes** [comment]
Thanks for reporting this! I think this is because of a problem in the `setup.py`. I will push a fix shortly.

**Comment by lantunes** [comment]
I have fixed the `setup.py` file and uploaded a new release. Please try again. The new version is `0.2.1`.

**Comment by kzuberi** [comment]
Yup fixed, thanks.
